name: fwd_map
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  maplibre_gl:
      git:
        url: https://github.com/m0nac0/flutter-maplibre-gl.git
        ref: main

  fwd_minimal_sdk:
      git:
        url: https://github.com/91team/fwd_minimal_sdk.git
        ref: main

  flutter_plugin_android_lifecycle: ^2.0.7
  http: ^0.13.5
  location: ^4.4.0
  screenshot: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg